name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: |
        ./gradlew --no-configuration-cache --no-parallel  assemble
        ./gradlew  --no-parallel :libdatachannel-java-arch-detect:build
    - name: Publish
      if: github.event_name == 'push' ||  github.event_name == 'release'
      run: |
        ./gradlew  --no-parallel  -Pgpr.user=${{ github.actor }} -Pgpr.key=${{ secrets.GITHUB_TOKEN }} -Pgpr.owner=${{ github.repository_owner }} publish
      
